version: '3'

services: 
  deliveryordermysqlimage:
    image: mysql:latest
    container_name: deliveryordermysqlimage
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=deliveryorderdb
      - MYSQL_USER=deliveryorderuser
      - MYSQL_PASSWORD=ThePassword
  deliveryorderwebimage:
    image: selvagurumanokaran/deliveryorder-web
    container_name: deliveryorderwebimage
    depends_on:
      - deliveryordermysqlimage
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=deliveryordermysqlimage
      - DATABASE_PORT=3306
      - DATABASE_NAME=deliveryorderdb
      - DATABASE_USER=deliveryorderuser
      - DATABASE_PASSWORD=ThePassword