version: '3'

services: 
  deliveryordermysqlimage:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=deliveryorderdb
      - MYSQL_USER=deliveryorderuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 3306:3306
  deliveryorderwebimage:
    image: selvagurumanokaran/deliveryorder-web
    depends_on:
      - deliveryordermysqlimage
    ports:
      - 8080:8080